ajdawson/eofs

.travis.yml

Updated the configuration for Travis-CI to use the official SciTools Binstar channel to obtain Iris. Later versions of the Iris conda package do not suffer from the UDUNITS2 bug that was previously worked-around. Testing for Python 3.4 is also added.

Update Travis-CI config to official SciTools channel.

---

lib/eofs/iris.py
lib/eofs/multivariate/iris.py
lib/eofs/tools/iris.py

This change prevents EOF analysis results from sharing coordinates with the input cube or other values returned from the solver.

Use copies of coordinates in iris interface.

---

lib/eofs/iris.py
lib/eofs/multivariate/iris.py

Replace direct inspection of input type with use of `isinstance`.

Use isinstance instead of directly checking type.

---

.travis.yml
lib/eofs/tools/standard.py

Version 1.10 of numpy had a regression where ma.dot no longer always returned a masked array. This is fixed in numpy 1.10.2 but there are users on 1.10.0 and 1.10.1 who are having problems with eofs so a quick fix could be useful.

Workaround for numpy regression.

---

.travis.yml
lib/eofs/tools/standard.py

The goal of this PR is to be able to provide a v0.5.1 release to avoid rushing v1.0. This branch has two cherry-picked commits from master:
* workaround for a bug in numpy 1.10
* enable containerised builds on travis
It also has a new commit which enables Python 3.4 and 3.5 testing (not worth a cherry-pick).

Backport numpy fix and CI improvements.

---

.travis.yml

This allows a build to be tested in both basic mode (without metadata interfaces) as well as complete mode (with metadata interfaces). The metadata interfaces impose other constraints on the environment (numpy version in particular) that we don't always want. This should avoid bugs like #34 being so surprising, as the basic test mode should always use the latest numpy.
Conda packages for Iris on Python 3.4 are anticipated in the near future, at which point the exclude for 3.4 can be removed.

Improve the build matrix.

---

.travis.yml

In testing mode "complete" tests on the iris interface are now run for Python 3, although only on Python 3.4 as binaries for the latest iris release are only available for Python 2.7 and 3.4.

Test the iris interface on Python 3.4.

---

README.md

Adds the full name of the analysis method in the first line of the README, lacking the description has been suggested as confusing (see #23).

Add description of EOFs to readme. Closes #23.

---

lib/eofs/tools/iris.py

It was hard-coded to 1 by mistake, it should have been the value passed through by the user.

Fix bug in setting ddof for iris covariance maps.

---

lib/eofs/__init__.py

A release branch for v1.1.x has been cut, bump the development version by a minor increment.

Advance development version to 1.2.

---

doc/devguide/testing.rst

This release is Python 3 compatible (you can run tests against the source) and the full test suite requires xarray in addition to cdms2 and iris.

Update testing documentation for v1.1.x.

---

lib/eofs/iris.py
lib/eofs/multivariate/iris.py
lib/eofs/tests/test_error_handling.py
lib/eofs/tools/iris.py

Changes the way time coordinates are identified in the iris interface. Previously the name had to include the string `'time'`, but this is changed to use the iris built-in checks for time units on a coordinate. If no time coordinates are found using this method we fall back to the previous method, so the change should be backwards compatible. See #68 for background.

Better identification of time coordinates.

---

lib/eofs/cdms.py
lib/eofs/tests/reference.py
lib/eofs/tests/utils.py

Update code to eliminate deprecation warnings from our dependencies when running the test suite. Only one change is in the library code, which ensures the cdms interface will work on later versions of numpy (although cdms2 itself currently does not support versions > 1.9).

Update for deprecations in dependencies

---

examples/cdms/hgt_example.py
examples/cdms/sst_example.py
examples/iris/hgt_example.py
examples/iris/sst_example.py
examples/standard/hgt_example.py
examples/standard/sst_example.py
examples/xarray/hgt_example.py
examples/xarray/sst_example.py

The example scripts now have a list of dependencies (outside the core eofs dependencies) required to run them.

Note additional dependencies in example programs.

---

README.md

Use the generic latest release DOI from Zenodo, this ensures the badge in the README will refer to the latest version.

Use latest version in Zenodo DOI badge

---

README.md
doc/index.rst

Use the `conda-forge` channel instead of `ajdawson`.

Instruct users to install from conda-forge channel

---

examples/cdms/hgt_example.py
examples/cdms/sst_example.py

Passing a cdms2 variable to matplotlib works for some cases but not others and is dependent on cdms2 version. The safest thing to do is pass the array contained by the variable instead.

Use data component of cdms2 variables for plotting

---

.travis.yml
lib/eofs/__init__.py
lib/eofs/cdms.py
lib/eofs/examples/__init__.py
lib/eofs/iris.py
lib/eofs/multivariate/__init__.py
lib/eofs/multivariate/cdms.py
lib/eofs/multivariate/iris.py
lib/eofs/multivariate/standard.py
lib/eofs/standard.py
lib/eofs/tests/__init__.py
lib/eofs/tests/test_error_handling.py
lib/eofs/tests/test_multivariate_error_handling.py
lib/eofs/tests/test_multivariate_solution.py
lib/eofs/tests/test_solution.py
lib/eofs/tests/test_tools.py
lib/eofs/tests/utils.py
lib/eofs/tools/__init__.py
lib/eofs/tools/cdms.py
lib/eofs/tools/generic.py
lib/eofs/tools/iris.py
lib/eofs/tools/standard.py
lib/eofs/tools/xarray.py
lib/eofs/xarray.py

Fixes an issue where floating point divide was being used instead of integer divide. Also ensures all modules import `division` from `__future__` so that behaviour is consistent on Python 2 and 3. The CI matrix has been updated to drop Python 3.3 and add Python 3.6, also including Iris for metadata interface tests on Python 3.5 and 3.6 now.

Fixes and updates for Python 3

---

.gitignore
.travis.yml
doc/devguide/testing.rst
lib/eofs/tests/__init__.py
lib/eofs/tests/test_coding_standards.py
lib/eofs/tests/test_error_handling.py
lib/eofs/tests/test_multivariate_error_handling.py
lib/eofs/tests/test_multivariate_solution.py
lib/eofs/tests/test_solution.py
lib/eofs/tests/test_tools.py
setup.cfg

The main switch is from nose to pytest for the test framework. In addition the pep8 library is replaced with pycodestyle.

Modernize the testing components

---

.travis.yml

This breaks away from the extremely old cdat-lite package and uses the cdms2 library from the UVCDAT release.

Test using cdms2 from UVCDAT

---

lib/eofs/standard.py
lib/eofs/tests/test_solution.py
lib/eofs/xarray.py

The Dask array library includes a parallel SVD solver. Use this to compute the EOF, provided the input data is a Dask array (e.g. from using `xarray.open_dataset(..., chunks={'time': 10})`)
Dask arrays are only used for the input to the EOF calculation. Because of the way that masking works the output from the SVD solver is converted into normal Numpy arrays. There should still be some benefit from the parallel SVD algorithm that Dask uses, though I've not measured performance.
Both the standard and Xarray solvers are supported. Iris can in theory use Dask, but I couldn't see how to set up test data for it.

Add support for Dask SVD solver

---

lib/eofs/standard.py

When dask import, use `dask.array.where` instead of `np.where`. This should resolve #143 and #122. The solution was originally suggested by @lfery and I extended it to consider the `has_dask` indicator (`True` when `dask` imported, and False for the opposite).

Bug fix for conflict between `dask` array and `np.where`
