.travis.yml
Should be a container-based build anyway since there is no sudo usage, but it doesn't hurt to be explicit.
=> Explicitly enable Travis container based build.

lib/eofs/iris.py
Keep AuxCoords from iris Cube's instead of throwing them away.
=> Retain AuxCoords in the iris interface.

lib/eofs/iris.py, lib/eofs/multivariate/iris.py
Use the preferred `if not list` instead of checking the length of the list is less than 1.
=> Better checks for empty lists.

lib/eofs/iris.py, lib/eofs/multivariate/iris.py, lib/eofs/tools/iris.py
Re-factors the existing AuxCoord support, pulling out common components for reuse.
=> Support AuxCoords in the iris multivariate solver.

doc/conf.py, doc/index.rst, doc/userguide/interfaces.rst
Update the documentation front-page, adding a clearer description of the package and install instructions for conda.
=> Update documentation for newer versions.

lib/eofs/multivariate/iris.py
Accidental middle mouse button press I suspect...
=> Remove erroneous section from docstring.

examples/cdms/hgt_example.py, examples/cdms/sst_example.py, examples/iris/hgt_example.py, examples/iris/sst_example.py, examples/standard/hgt_example.py, examples/standard/sst_example.py
Use cartopy in standard and cdms examples.
=> Update examples to use Cartopy for mapping.

lib/eofs/cdms.py, lib/eofs/iris.py, lib/eofs/multivariate/cdms.py, lib/eofs/multivariate/iris.py, lib/eofs/multivariate/standard.py, lib/eofs/standard.py, lib/eofs/tests/reference.py, lib/eofs/tests/test_multivariate_error_handling.py, lib/eofs/tests/test_multivariate_solution.py, lib/eofs/tests/test_solution.py, lib/eofs/tools/iris.py, lib/eofs/tools/standard.py
Update years in license headers where necessary.
=> Copyright corrections

lib/eofs/__init__.py
Previously it was set for a v0.6 release, but it has been decided to go to the v1.0 series for the next release.
=> Set main branch for a version 1 release.

doc/api/eofs.tools.rst, doc/index.rst
Corrects a couple of very minor issues in the documentation.
=> Apply minor corrections in the documentation.

README.md, doc/index.rst
Update the README file with more modern references to UV-CDAT and update the install section with conda/pip instructions.
=> Refresh README and install instructions.

doc/conf.py, doc/gh-pages.py, lib/eofs/cdms.py, lib/eofs/iris.py, lib/eofs/multivariate/cdms.py, lib/eofs/multivariate/iris.py, lib/eofs/multivariate/standard.py, lib/eofs/tests/__init__.py, lib/eofs/tests/reference.py, lib/eofs/tests/test_error_handling.py, lib/eofs/tests/test_multivariate_error_handling.py, lib/eofs/tests/test_multivariate_solution.py, lib/eofs/tests/test_solution.py, lib/eofs/tests/test_tools.py, lib/eofs/tests/utils.py, lib/eofs/tools/generic.py, lib/eofs/tools/iris.py, setup.py
This PR attempts to make the source code compatible with both Python 2 and 3 simultaneously, and therefore removes the need for using `2to3` on Python 3.
=> Make source Python 3 compatible.

.travis.yml, doc/devguide/testing.rst, examples/cdms/hgt_example.py, examples/cdms/sst_example.py, lib/eofs/iris.py, lib/eofs/multivariate/iris.py, lib/eofs/multivariate/standard.py, lib/eofs/standard.py, lib/eofs/tests/__init__.py, lib/eofs/tests/reference.py, lib/eofs/tests/test_coding_standards.py, lib/eofs/tests/test_error_handling.py, lib/eofs/tests/test_multivariate_error_handling.py, lib/eofs/tests/test_multivariate_solution.py, lib/eofs/tests/test_solution.py, lib/eofs/tests/test_tools.py, lib/eofs/tests/utils.py, lib/eofs/tools/iris.py, setup.py
Make the code base PEP8 compliant. Also adds a test to ensure the library code remains PEP8 compliant. Documentation is updated to reflect the new dependency.
=> PEP8 compliance and a test for compliance.

lib/eofs/iris.py
Reference to cdms2 changed to iris.
=> Fix error in iris projectField docstring.

.travis.yml, README.md, doc/api/eofs.xarray.rst, doc/api/index.rst, doc/conf.py, doc/examples/elnino_xarray.rst, doc/examples/index.rst, doc/examples/nao_xarray.rst, doc/examples/xarray_examples_index.rst, doc/index.rst, doc/userguide/interfaces.rst, doc/userguide/usage.rst, examples/iris/hgt_example.py, examples/standard/hgt_example.py, examples/xarray/hgt_example.py, examples/xarray/sst_example.py, lib/eofs/__init__.py, lib/eofs/tests/reference.py, lib/eofs/tests/test_error_handling.py, lib/eofs/tests/test_solution.py, lib/eofs/tests/test_tools.py, lib/eofs/tools/generic.py, lib/eofs/tools/xarray.py, lib/eofs/xarray.py
This PR adds an [xarray](http://xarray.pydata.org) interface for EOF solution. It does not include a multivariate solver interface, this can wait for another PR.
=> Add an xarray interface

MANIFEST.in
Make sure the README and license file are distributed along with the source.
=> Add a manifest file.

doc/userguide/speed.rst
MKL optimizations in Anaconda are now free: https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations.
=> Update userguide section on optimization.

.travis.yml
The build matrix is complex due to different optional dependency availability of each Python version. An explicit method is therefore favoured.
=> Improve the build matrix on Travis CI.

README.md, doc/index.rst
Add DOI badges and citation sections to the README, and add a citation section to the documentation front page.
=> Add citation information

lib/eofs/tests/reference.py, lib/eofs/xarray.py
Replaced xr.Coordinate with xr.IndexVariable.
Also made the edit of the ticket by @lynch123.
=> Update for deprecations in xarray.py

.travis.yml, lib/eofs/tools/cdms.py
The first goal is to test everything on Python 3. Once that is working any failing tests can be fixed.
=> Update Travis CI configuration

lib/eofs/xarray.py
This fixes #123 by just calling data on the coordinate object.
=> Fix preserving non-dimension coordinates with latest xarray

README.md
Document website link is outdated
=> document website link change

.pre-commit-config.yaml, lib/eofs/standard.py, pyproject.toml
Update the checker/linters and fix issues highlighted by the updated version of each check/linter.
=> Updates to checks in pre-commit config
